### ISSUE TITLE
剧番下载部分一直没有监控中

### ISSUE THREAD

**Issue by Zhang-abab** [LuckyPuppy514/automatic-theater#10]
更新后使用没有任何问题，在电影检索下载部分很爽。一键式。但是所添加的所有番剧一直显示监控中，图中以美剧Loki为例
![0125-1327](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/4893caa3-f564-4974-aee0-a76f18a6db88)
![0125-1346](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/76b5a59d-ad8d-4609-bcae-b581a1d25068)

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/automatic-theater/assets/53246532/6da100fc-0deb-4d29-b5c7-80ff551694cf)
![image](https://github.com/LuckyPuppy514/automatic-theater/assets/53246532/f5e7c228-0db0-4d76-b745-3aef1b6723c9)

你可以在 Jellyseerr 中开启自动搜索，这样第一次添加的时候，历史的所有集数也会自动搜索一次
但是我个人不推荐，我建议个人搜索整季的合集手动下载，否则集数太多，很多站点都会挂掉，而且单集质量一般不如合集

![image](https://github.com/LuckyPuppy514/automatic-theater/assets/53246532/929cafc5-bdd6-456d-9b22-814f5781cc9a)

另外，已经播出的剧集，如果没有人重新发布，即使监控中也不会下载，需要手动点击下面的按钮才会搜索历史发布的数据

![image](https://github.com/LuckyPuppy514/automatic-theater/assets/53246532/31ddcbdb-3348-4ba8-bf9c-bef1808e8ea3)

**Comment by Zhang-abab** [comment]
按照你第二个方法尝试了之后还是没办法
![0125-1705](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/5e250862-d7a7-48fb-b16d-1a26723088f7)
![0125-1704](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/251c8512-abb7-4870-bbf7-bdbc31628217)

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/automatic-theater/assets/53246532/7e33a4d0-21af-40bf-8fa1-ca0d9e4b4350)

那试试这里，如果没有数据，说明你的索引器就是找不到，只能自己去找几个PT站点加上了

**Comment by Zhang-abab** [comment]
点开这个小人是这个样子，又有内容
![截屏2024-01-25 20 36 29](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/3718ed45-520b-4f6f-93ee-11e417f31d09)

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/automatic-theater/assets/53246532/4cf5f4ec-ed53-475e-8a2a-79b4e6687bf4)

你要自己看是什么原因导致拒绝的

**Comment by Zhang-abab** [comment]
好像是什么什么分辨率，我现在缓存的三个报错都不一样
![截屏2024-01-25 22 09 28](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/1213bc36-a6c7-4eb2-89d9-f70e3cd32ea7)
![截屏2024-01-25 22 10 19](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/737a91ef-7614-4229-b58b-fd79c9b248e7)
![截屏2024-01-25 22 10 39](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/e723d9dc-a1ab-4b72-8722-9c6b302d5392)

**Comment by LuckyPuppy514** [comment]
你自己选的 1080P 配置，默认是需要中文的，你自己可以修改

![20240125221408](https://github.com/LuckyPuppy514/automatic-theater/assets/53246532/913930d0-502a-4838-a6de-d03336545562)

建议复制一个配置，改这个最小分数，根据自己的需求进行更改

另外这些都是使用的问题，我这里没办法一个一个教你怎么使用，建议自己多尝试多找教程，学习如何使用
