### ISSUE TITLE
大佬这一套流程怎么如何自己也做一个

### ISSUE THREAD

**Issue by yl948** [LuckyPuppy514/automatic-theater#3]
大佬能否出一个大包迁移的过程，想自己也打包一下放github然后这样拉取

**Comment by LuckyPuppy514** [comment]
只需把 docker 持久化目录提取出来就行了，可以删除一些不需要的信息，如日志，备份文件等
如果打算放到公共仓库，注意下隐私信息

**Comment by yl948** [comment]
好的感谢大佬

**Comment by LuckyPuppy514** [comment]
> 好的感谢大佬

会用 git 的话，可以参考 [.gitignore](https://github.com/LuckyPuppy514/automatic-theater/blob/main/.gitignore) 把不需要上传的文件忽略掉就行了
