### ISSUE TITLE
部署全部没有问题但是无法使用

### ISSUE THREAD

**Issue by Zhang-abab** [LuckyPuppy514/automatic-theater#9]
根据现有的文档部署起来是完全没有问题，但是在使用Jellyseerr时无法加载出视频墙，进行搜索时也无资源。为排查问题使用Radarr、Sonarr进行搜索均显示资源缺失。最后使用Jackett却能搜索到视频资源。主要就是无法检索到资源从而无法完成下载等后续操作。感谢大佬无私奉献！！！！！！！！！！！

**Comment by Zhang-abab** [comment]
![Uploading 截屏2024-01-13 23.00.48.png…]()

**Comment by Zhang-abab** [comment]
![Uploading 截屏2024-01-13 23.00.48.png…]()

**Comment by Zhang-abab** [comment]
![截屏2024-01-13 23 00 59](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/ab32d397-dc28-4493-b8ba-85c527824c52)
![截屏2024-01-13 23 01 07](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/0be7faa3-b67f-4ba0-b5ef-518ab2fb7830)

**Comment by Zhang-abab** [comment]
![截屏2024-01-13 23 00 48](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/ffd88b20-3bf8-436a-b794-7da3c563dad4)
![截屏2024-01-13 23 00 59](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/aa74edaf-a63f-403f-9eaf-fb5ff1ad91d8)
![截屏2024-01-13 23 01 07](https://github.com/LuckyPuppy514/automatic-theater/assets/68942943/726e306f-8d80-4ddf-86f2-f0f255b44684)

**Comment by LuckyPuppy514** [comment]
Jellyseerr 无法加载海报墙一般是你的网络问题导致的，这个只能自行解决
其他应用需要等我更新，因为当前版本跟当初我调试的版本差异较大，等我明天有空更新一版

**Comment by Zhang-abab** [comment]
Jellyseerr 能单独设置代理嘛，大佬你也是铁人。高强度上网冲浪选手。

**Comment by Zhang-abab** [comment]
其实我现在的方案是用qb下载之后上传到Alist。再在Alist上面挂微软的5T盘。然后用玩客云挂Alist挂载到本地，再用Emby海报墙。矿渣利用。所以你这个全套方案真的是相当舒服了，可以直接用强无敌。看到你秒回我都恍惚了，高强度冲浪选手🏄

**Comment by LuckyPuppy514** [comment]
新版本已经发布
